delete from meta_table;
insert into meta_table(name,description,decl_module_name, decl_name) values ('app_user','','protoapp.db','AppUserTable');
insert into meta_table(name,description,decl_module_name, decl_name) values ('message','','protoapp.db','MessageTable');

delete from meta_adl_decl;
insert into meta_adl_decl(module_name,name,decl) values ('protoapp.db','AppUserTable', '{"name":"AppUserTable","version":"nothing","type_":{"newtype_":{"typeParams":[],"typeExpr":{"typeRef":{"reference":{"moduleName":"common.db","name":"WithId"}},"parameters":[{"typeRef":{"reference":{"moduleName":"protoapp.db","name":"AppUser"}},"parameters":[]}]},"default":"nothing"}},"annotations":[{"k":{"moduleName":"common.db","name":"DbTable"},"v":{"extra_sql":["grant select on app_user to admin_user;"],"indexes":[["email"]],"uniqueness_constraints":[["email"]]}}]}');
insert into meta_adl_decl(module_name,name,decl) values ('common.db','WithId', '{"name":"WithId","version":"nothing","type_":{"struct_":{"typeParams":["T"],"fields":[{"name":"id","serializedName":"id","typeExpr":{"typeRef":{"primitive":"String"},"parameters":[]},"default":"nothing","annotations":[{"k":{"moduleName":"common.db","name":"DbPrimaryKey"},"v":null}]},{"name":"value","serializedName":"value","typeExpr":{"typeRef":{"typeParam":"T"},"parameters":[]},"default":"nothing","annotations":[{"k":{"moduleName":"common.db","name":"DbSpread"},"v":null}]}]}},"annotations":[{"k":{"moduleName":"sys.annotations","name":"Doc"},"v":"Extent a datatype for use as a database table, giving it a\nprimary key\n"}]}');
insert into meta_adl_decl(module_name,name,decl) values ('protoapp.db','AppUser', '{"name":"AppUser","version":"nothing","type_":{"struct_":{"typeParams":[],"fields":[{"name":"fullname","serializedName":"fullname","typeExpr":{"typeRef":{"reference":{"moduleName":"common.strings","name":"StringNE"}},"parameters":[]},"default":"nothing","annotations":[]},{"name":"email","serializedName":"email","typeExpr":{"typeRef":{"reference":{"moduleName":"common.strings","name":"StringNE"}},"parameters":[]},"default":"nothing","annotations":[]},{"name":"isAdmin","serializedName":"isAdmin","typeExpr":{"typeRef":{"primitive":"Bool"},"parameters":[]},"default":"nothing","annotations":[]},{"name":"hashed_password","serializedName":"hashed_password","typeExpr":{"typeRef":{"reference":{"moduleName":"common.strings","name":"StringNE"}},"parameters":[]},"default":{"just":""},"annotations":[]}]}},"annotations":[]}');
insert into meta_adl_decl(module_name,name,decl) values ('common.strings','StringNE', '{"name":"StringNE","version":"nothing","type_":{"type_":{"typeParams":[],"typeExpr":{"typeRef":{"primitive":"String"},"parameters":[]}}},"annotations":[{"k":{"moduleName":"common.ui","name":"ValidRegex"},"v":{"description":"non empty","regex":"^.*\\S+.*$","returnGroup":0}},{"k":{"moduleName":"sys.annotations","name":"Doc"},"v":"A string that isn''t empty, and isn''t only whitespace.\n"}]}');
insert into meta_adl_decl(module_name,name,decl) values ('protoapp.db','MessageTable', '{"name":"MessageTable","version":"nothing","type_":{"newtype_":{"typeParams":[],"typeExpr":{"typeRef":{"reference":{"moduleName":"common.db","name":"WithId"}},"parameters":[{"typeRef":{"reference":{"moduleName":"protoapp.db","name":"Message"}},"parameters":[]}]},"default":"nothing"}},"annotations":[{"k":{"moduleName":"common.db","name":"DbTable"},"v":{"extra_sql":["grant all on message to admin_user;"],"indexes":[["posted_at"]]}}]}');
insert into meta_adl_decl(module_name,name,decl) values ('protoapp.db','Message', '{"name":"Message","version":"nothing","type_":{"struct_":{"typeParams":[],"fields":[{"name":"posted_at","serializedName":"posted_at","typeExpr":{"typeRef":{"reference":{"moduleName":"common.time","name":"Instant"}},"parameters":[]},"default":"nothing","annotations":[]},{"name":"posted_by","serializedName":"posted_by","typeExpr":{"typeRef":{"reference":{"moduleName":"protoapp.db","name":"AppUserId"}},"parameters":[]},"default":"nothing","annotations":[]},{"name":"message","serializedName":"message","typeExpr":{"typeRef":{"reference":{"moduleName":"common.strings","name":"StringML"}},"parameters":[]},"default":"nothing","annotations":[]}]}},"annotations":[]}');
insert into meta_adl_decl(module_name,name,decl) values ('common.time','Instant', '{"name":"Instant","version":"nothing","type_":{"newtype_":{"typeParams":[],"typeExpr":{"typeRef":{"primitive":"Int64"},"parameters":[]},"default":"nothing"}},"annotations":[{"k":{"moduleName":"common.db","name":"DbColumnType"},"v":"timestamp with time zone"},{"k":{"moduleName":"sys.annotations","name":"Doc"},"v":"A instant in time, represented as milliseconds from\nthe epoch of \"1970-01-01T00:00:00Z\n"}]}');
insert into meta_adl_decl(module_name,name,decl) values ('protoapp.db','AppUserId', '{"name":"AppUserId","version":"nothing","type_":{"type_":{"typeParams":[],"typeExpr":{"typeRef":{"reference":{"moduleName":"common.db","name":"DbKey"}},"parameters":[{"typeRef":{"reference":{"moduleName":"protoapp.db","name":"AppUserTable"}},"parameters":[]}]}}},"annotations":[]}');
insert into meta_adl_decl(module_name,name,decl) values ('common.db','DbKey', '{"name":"DbKey","version":"nothing","type_":{"newtype_":{"typeParams":["T"],"typeExpr":{"typeRef":{"primitive":"String"},"parameters":[]},"default":"nothing"}},"annotations":[{"k":{"moduleName":"sys.annotations","name":"Doc"},"v":"A reference for a database stored value, referenced by a\nstring primary key.\n"}]}');
insert into meta_adl_decl(module_name,name,decl) values ('common.strings','StringML', '{"name":"StringML","version":"nothing","type_":{"type_":{"typeParams":[],"typeExpr":{"typeRef":{"primitive":"String"},"parameters":[]}}},"annotations":[{"k":{"moduleName":"sys.annotations","name":"Doc"},"v":"A multi line, free-form text string\n"}]}');
